meteo:
    path: /
    host: "{subdomain}.ustisha.ru"
    defaults:
        subdomain: meteo
    requirements:
        subdomain: meteo|dev.meteo
    controller: App\Controller\MeteoController::index

index:
    path: /{reactRouting}
    defaults: { _controller: App\Controller\DefaultController::index, reactRouting: null }
    requirements:
        reactRouting: "^(signin).+"

user:
    path: /user
    controller: App\Controller\AuthController::current
    methods: GET

login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: POST

logout:
    path: /logout
    controller: App\Controller\AuthController::logout
    methods: GET

log_table:
    path: /log/table/{page}
    controller: App\Controller\LogController::table

app_lora_receive:
    path: /lora/receive
    controller: App\Controller\LoraController::receive